# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47af0181dd3735f0ed49d326f5c4d4fd7f047222f9c0f3afe77b7234260d06870f14daac7a5fcbe9db2d541dd14df8091cd89a97bb67bf6a8503e6b2bcf69552

test:
  secret_key_base: 09957d5916d0d48c199a3aad78d3f1f4b5c667a89ac3af47f397601a2996e03ce83f41d5ff0af110db69bb8cc91b85628845632b9812369753a6f877ab220e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
